name: Docker Build and Push

on:
  push:
    branches: [ release ]
    #paths:
    #- src/**
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag moonglade:latest
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,v12.16.3"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy the Docker app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        script_stop: true
        script: |
          sudo docker stop $(sudo docker ps --filter name=pzyio-blog -q)
          sudo docker rm -f $(sudo docker ps -a --filter name=pzyio-blog -q)
          sudo docker rmi -f $(sudo docker images ${{ secrets.DOCKER_REPOSITORY }}:latest -q)
          sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
          sudo docker run -d --net=host ${{ secrets.RUN_ENVIRONMENT }} ${{ secrets.FILE_LINK }} --restart=always --name=pzyio-blog ${{ secrets.DOCKER_REPOSITORY }}:latest

